FROM node:lts-alpine

# update npm 
RUN npm install -g npm@latest

# install serve for serving static content
RUN npm install -g serve

# make the 'app' folder the current working directory
WORKDIR /app

# copy 'dist' folder
COPY frontend/dist dist

EXPOSE 8080

CMD [ "serve", "-s", "dist", "-l", "8080" ]
