FROM node:lts-alpine

# update npm 
RUN npm install -g npm@latest

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy 'dist' folder
COPY frontend/dist dist

EXPOSE 8080

CMD [ "http-server", "dist" ]