FROM python:3.10-buster

# Install dependencies
RUN apt-get update \
    && apt-get install -y build-essential libpq-dev gettext libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Installs the dependencies used by Chrome and Selenium
RUN apt-get install --yes --quiet --no-install-recommends \
    gettext \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libx11-6 \
    libxcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    libxshmfence1 \
    wget \
    xdg-utils \
    netcat \
    xvfb \
 && rm -rf /var/lib/apt/lists/*

# Install Chrome
RUN dpkg -i ./bin/google-chrome.deb

# Set up app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Python dependencies
COPY ./backend/requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Copy over the app code
COPY ./backend .

# Install Chrome
RUN dpkg -i ./bin/google-chrome.deb


# Convert line endings of runserver.sh
RUN apt-get update && apt-get install -y dos2unix && dos2unix runserver.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# Set up the runserver.sh script
RUN chmod +x runserver.sh

# Expose the port that the app listens on
EXPOSE 80

# Start the app with the runserver.sh script
CMD ["/bin/bash", "./runserver.sh"]