FROM python:3.10.10-slim

# Install dependencies
RUN apt-get update \
    && apt-get install -y build-essential libpq-dev gettext libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Python dependencies
COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Copy over the app code
COPY . .

# Convert line endings of runserver.sh
RUN apt-get update && apt-get install -y dos2unix && dos2unix runserver.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# Set up the runserver.sh script
RUN chmod +x runserver.sh

# Expose the port that the app listens on
EXPOSE 80

# Start the app with the runserver.sh script
CMD ["/bin/bash", "./runserver.sh"]