FROM python:3.10.10-slim

# Set up app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy over the app code
COPY ./backend .

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential libpq-dev gettext libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info gnupg wget \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && apt-get update \
    && apt-get install -y --no-install-recommends google-chrome-stable \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Convert line endings of runserver.sh
RUN apt-get update && apt-get install -y dos2unix && dos2unix runserver.sh && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# Set up the runserver.sh script
RUN chmod +x runserver.sh

# Expose the port that the app listens on
EXPOSE 80

# Start the app with the runserver.sh script
CMD ["/bin/bash", "./runserver.sh"]