# Generated by Django 4.1.2 on 2022-11-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
