# Generated by Django 4.1.2 on 2022-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyprofile_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
