# Generated by Django 4.1.2 on 2023-04-04 20:39

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_companyprofile_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.get_company_logo_upload_path),
        ),
    ]
