# Generated by Django 4.1.2 on 2023-04-05 13:43

import company.models
import company.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyprofile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=company.models.get_company_logo_upload_path, validators=[company.validators.validate_logo_file_size]),
        ),
    ]
