# Generated by Django 4.1.2 on 2023-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_job_id_job_job_link_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
