# Generated by Django 4.1.2 on 2023-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='number_of_positions',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(blank=True, default='Full Time', max_length=100, null=True),
        ),
    ]
