# Generated by Django 4.1.2 on 2023-03-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_appliedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
