# Generated by Django 4.1.2 on 2022-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
