# Generated by Django 4.1.2 on 2022-11-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='software_field',
        ),
    ]
