# Generated by Django 4.1.2 on 2023-03-31 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeeprofile_software_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='about',
        ),
    ]
