# Generated by Django 4.1.2 on 2023-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_employeeprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
