# Generated by Django 4.1.2 on 2023-04-05 13:43

from django.db import migrations, models
import employee.models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeeprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=employee.models.get_resume_upload_path, validators=[employee.validators.validate_picture_file_size]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=employee.models.get_picture_upload_path, validators=[employee.validators.validate_file_size]),
        ),
    ]
