# Generated by Django 4.1.2 on 2022-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_pic_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
