# Generated by Django 4.1.2 on 2022-11-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employeeprofile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='Portfolio_url',
            new_name='portfolio_url',
        ),
    ]
