# Generated by Django 4.1.2 on 2022-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_employeeprofile_expected_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='expected_salary',
            field=models.IntegerField(default=0),
        ),
    ]
