# Generated by Django 4.1.2 on 2022-11-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employeeprofile_expected_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
