# Generated by Django 4.1.2 on 2023-04-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
